title: "Klest Dedja"
description: "AI Research Scientist | Explainable AI | Forecasting | DevOPS in progress"
theme: jekyll-theme-cayman
url: "https://klestdedja.github.io"

nav:
  - { title: "(back to) homepage", url: "/" }
  - { title: "my CV", url: "/cv" }
  - { title: "my repositories", url: "/repositories" }
