title: "Klest Dedja"
description: "AI Research Scientist | Explainable AI | Forecasting | DevOPS in progress"
theme: jekyll-theme-cayman
url: "https://klestdedja.github.io"

nav:
  - { title: "Homepage", url: "/" }
  - { title: "Curriculum Vitae", url: "/cv" }
  - { title: "Recent projects", url: "/repositories" }
